### ISSUE TITLE
I get a problem when I use cmake to build veccore with argument -USMSIMD=ON

### ISSUE THREAD

**Issue by jimbook** [root-project/veccore#22]
I get a problem when I use cmake to build veccore with argument -USMSIMD=ON.When I cmake the VecCore with argument -UMESIMD=ON after I installed UME::SIMD(which is depended by VecCore) by following its install tutorial, it raise an error like this:
> CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
>   Could NOT find UMESIMD (missing: UMESIMD_INCLUDE_DIRS) (Required is at
>   least version "0.8.1")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
>   cmake/FindUMESIMD.cmake:63 (find_package_handle_standard_args)
>   cmake/Builtins.cmake:14 (_find_package)
>   CMakeLists.txt:51 (find_package)

Then I try using `cmake && make && make install` in the UME::SIMD folder to add UME::SIMD to cmake module, but it doesn't work.Below is how I install UME::SIMD:
```bash
$ mkdir ~/software/ume
$ cd ~/software/ume
$ git clone https://github.com/edanor/umesimd.git
$ cd umesimd
$ git checkout tags/v0.8.1
$ cd ..
$ pwd
/home/jimbook/software/ume
$ export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/home/jimbook/software/ume
$ echo  "#export the UME::SIMD library directory" >> ~/.bachrc
$ echo  "export CPLUS_INCLUDE_PATH=\$CPLUS_INCLUDE_PATH:/home/jimbook/software/ume" >> ~/.bachrc
$ mkdir build
$ cd build
$ cmake ..
$ make &amp;&amp; sudo make install
```

**Comment by amadio** [comment]
UME::SIMD is inactive since a long time and I am considering removing support for it from VecCore. I strongly encourage you to choose the `std::simd` backend if you want to support AVX512. UME::SIMD is slower than Vc everywhere else.

As for installation, you need to give CMake a proper path so it can find dependencies, just exporting `CPLUS_INCLUDE_PATH` is not enough. For convenience during testing, I added an option that lets Vc and/or UME::SIMD be installed along with VecCore, which you can enable with `-DBUILD_VC=ON` and `-DBUILD_UMESIMD=ON`. If you don't build VecCore's own tests, no build actually needs to happen (except for Vc), only the headers get installed all in the same place.

**Comment by jimbook** [comment]
> UME::SIMD is inactive since a long time and I am considering removing support for it from VecCore. I strongly encourage you to choose the `std::simd` backend if you want to support AVX512. UME::SIMD is slower than Vc everywhere else.
> 
> As for installation, you need to give CMake a proper path so it can find dependencies, just exporting `CPLUS_INCLUDE_PATH` is not enough. For convenience during testing, I added an option that lets Vc and/or UME::SIMD be installed along with VecCore, which you can enable with `-DBUILD_VC=ON` and `-DBUILD_UMESIMD=ON`. If you don't build VecCore's own tests, no build actually needs to happen (except for Vc), only the headers get installed all in the same place.

Thanks for your reply, it's really helpful for me and solved my problem.
